name: Daily Map Generator

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Map Generator Script
      run: python generate_map.py

    - name: Force README daily update
      run: |
        DATE=$(date +'%Y-%m-%d')
        sed -i "/^Last Updated:/d" README.md
        echo "Last Updated: ${DATE}" >> README.md

    - name: Commit and Push changes
      run: |
        git config --global user.name "Daily Map Generator"
        git config --global user.email "Example@github.com"

        git add README.md today_map.json

        git commit -m "Daily Map Update: $(date +'%Y-%m-%d')" || exit 0
        git push
